### ISSUE TITLE
petstore这个例子前端运行不了

### ISSUE THREAD

**Issue by fqtyfz** [lealone/Lealone-Examples#10]
前端一片空白，v-replace不是vue的指令吧，做了扩展吗？

**Comment by codefollower** [comment]
我试了一下，看到后端出异常了，是前几天我把 lealone orm 框架编码 model 对象为 json 字符串时出错了

**Comment by codefollower** [comment]
[问题已经修复](https://github.com/lealone/Lealone/commit/25d6ee3fe8d6d5dd21f4033229ea1ff4a33c040b)，感谢报告问题。

lealone 最新的 SNAPSHOT 版本已经提交到 maven 仓库，
重新打包构建 petstore 再运行就可以了。 

v-replace 是我加的指令，只在打包构建阶段有用，运行时就没有了， vue 是看不到它的。

**Comment by codefollower** [comment]
petstore\petstore-web\web 这里的前端模板只是我们自己的方案，lealone 不涉及前段 ui 框架，前端框架可以随便选，用 jQuery 用 vue 都可以。
