### ISSUE TITLE
lealone微服务隐式传参

### ISSUE THREAD

**Issue by jiliapp** [lealone/Lealone-Examples#12]
不知道怎么描述，描述一个常使用的场景吧，
1.假设我有一个登陆接口，验证用户名密码后签发一个token给客户端
2.客户端再次请求的时候，在header中传递token，一般会在spring gateway中解析token出来一个userId用户标识，并传递给业务系统
3.业务系统在需要知道他身份的时候，直接获取这个userId即可

疑惑: 怎么在lealone微服务系统中xx-service服务中获得这么一个userId？

**Comment by jiliapp** [comment]
spring cloud 使用比较多，出发看点都是基于spring cloud的业务系统中需要用到的。

**Comment by codefollower** [comment]
这种是跟 web 相关的东西了，lealone 微服务框架不干预 web 层的东西，只是兼容 http 协议允许前端直接调用后端服务。

你说的这种就是很常见的类似 session id 的功能，petstore 那个应用也有 userId 和购物车 ID，不过是在前端用 localStorage 来做的，不依赖具体的前后端框架，调用后端服务时，把这样的 session id 传过去。

这种方式确实每次只要后端服务需要用到这样的 id 都要在前端传一次，好处就是不依赖具体框架。

如果想依赖具体的框架，lealone 也有一种省事的办法，
petstore 那个应用在 petstore-web 模块下有一个 PetStoreRouterFactory 类，
是依赖 vertx web 做的，只要定义一个 /service/* 的 route 拦截一下，
在 header 中取出 token， 解析 token 把 userId 拿出来，
然后 routingContext.request().params().set("userId ", userId)，这样后面被调用的服务就自动被传递 userId 了。

**Comment by codefollower** [comment]
你用 create-lealone-app-5.0.0.jar 创建的 lealone 应用默认在 web 模块下就有一个 XXXRouterFactory，这个类就是专门处理特殊的 web 问题，包括文件上传、重定向、服务调用拦截、session 管理等等，我们用 lealone 开发的实际项目都是这么做的。

一个服务框架是不可能把 web 相关的功能都重复做掉的，我们的实际项目把 1% 的跟 web 相关的功能都拿到 XXXRouterFactory 去做。但是其他以前在 spring boot 里很多需要写的 Controller 都直接转成服务调用的方式了。

只要记住一点：
**xxx-service 那个模块不涉及 web 相关的东西，既可以让前端调用，也能被后端其他业务系统调用，web 相关的统一放到 xxx-web 模块。**

**Comment by codefollower** [comment]
[OpsCenterRouterFactory](https://github.com/lealone/Lealone-OpsCenter/blob/main/opscenter-web/src/main/java/org/lealone/opscenter/web/OpsCenterRouterFactory.java)

这个类非常接近你想要的功能了，从它改改
