### ISSUE TITLE
windows idea 系统找不到指定的路径

### ISSUE THREAD

**Issue by gongsongping** [lealone/Lealone-Examples#13]
petstore, windows eclipse 能正常跑起来, 页面也能显示出来,
但是windows idea能跑起来, 页面却显示不出来, 查看log发现路径不对
D:\lealone\Lealone-Examples\petstore-web\web\home\index.html (系统找不到指定的路径。)
正确路径应该是:
D:\lealone\Lealone-Examples\petstore\petstore-web\web\home\index.html

log:
NFO 21:28:17.787 TcpServer started, host: 127.0.0.1, port: 9210
INFO 21:28:18.469 Web root: ../petstore-web/web
INFO 21:28:18.470 Sockjs path: /_lealone_sockjs_/*
INFO 21:28:18.470 HttpServer is now listening on port: 9000
INFO 21:28:18.470 HttpServer started, host: 127.0.0.1, port: 9000
INFO 21:28:18.470 Total time: 1525 ms (Load config: 181 ms, Init: 658 ms, Start: 686 ms)
INFO 21:28:18.471 Exit with Ctrl+C
ERROR 21:28:26.830 Unhandled exception in router
java.io.FileNotFoundException: D:\lealone\Lealone-Examples\petstore-web\web\home\index.html (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]

**Comment by codefollower** [comment]
修改 [/petstore-test/src/test/resources/lealone.yaml](https://github.com/lealone/Lealone-Examples/blob/main/petstore/petstore-test/src/test/resources/lealone.yaml) 配置文件中的 web_root 参数，
把它改成 **petstore-web/web** 即可，不用 ../ 了。

IDEA 的当前工作目录确实跟 eclipse 差别很大。

**Comment by codefollower** [comment]
问题已经修复，Lealone 和 PetStore 都做了一些修改

[89aa951d6a17bdf667f6cf5159e4284ae10db56d](https://github.com/lealone/Lealone-Examples/commit/89aa951d6a17bdf667f6cf5159e4284ae10db56d)

https://github.com/lealone/Lealone/commit/d9e3daca9d5259074aca13528d5e9ded8f468583
https://github.com/lealone/Lealone/commit/d9e3daca9d5259074aca13528d5e9ded8f468583

更新一下代码即可，感谢报告问题。
