### ISSUE TITLE
js里使用orm

### ISSUE THREAD

**Issue by gongsongping** [lealone/Lealone-Examples#14]
多语言里, 比如js的service里能使用orm吗? 怎么用?

**Comment by codefollower** [comment]
orm 还没有封装出一层 js 接口，如果现在想用 js 访问 java 代码，只能用 GraalVM 的原始 API
参考这个 [JavaInteroperability](https://www.graalvm.org/22.1/reference-manual/js/JavaInteroperability/)

直接在 js 代码里用 orm 的 Model 子类，
比如创建 User 这个 Model  类的实例:

`var user = new (Java.type('my.model.User'))`

获得 User 这个 Model  类的 dao:
`var dao = Java.type('my.model.User').dao`

剩下的代码就跟 java 的版本一样了:

`user.name.set("test").phone.set(456).insert();`

**Comment by codefollower** [comment]
我增加了一个 js 使用 lealone orm 的例子可以跑的，你看看:
[user_service.js](https://github.com/lealone/Lealone-Polyglot/blob/main/lealone-js/src/test/resources/js/user_service.js)

**Comment by codefollower** [comment]
js 使用 lealone orm 的例子

[基于ORM框架使用JavaScript开发一个全栈微服务应用](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E5%9F%BA%E4%BA%8EORM%E6%A1%86%E6%9E%B6%E4%BD%BF%E7%94%A8JavaScript%E5%BC%80%E5%8F%91%E4%B8%80%E4%B8%AA%E5%85%A8%E6%A0%88%E5%BE%AE%E6%9C%8D%E5%8A%A1%E5%BA%94%E7%94%A8.md)
