### ISSUE TITLE
spring-demo 模块打包运行问题

### ISSUE THREAD

**Issue by vvinnpy** [lealone/Lealone-Examples#17]
- 在 ide 中能直接运行
- 编译打包配置有问题

**Comment by codefollower** [comment]
需要用 spring-boot-maven-plugin 的方式打包
mvn package spring-boot:repackage

然后运行
java -jar target/lealone-spring-demo-1.0.0.jar

这种方式打包后 spring boot 的 Controller 可以访问，但是 Lealone 的服务我发现找不到类，还在查原因。

**Comment by codefollower** [comment]
用各种参数试了 spring-boot-maven-plugin 和 maven-shade-plugin，对 spring boot 应用打出的包在运行时都不能正确使用 java compiler api 编译 java 源代码，反而用 eclipse 导出的 jar 包能正确运行。就像截图那样导出 jar 包，只有圈出来的那一项正确，其他的都不对。 ​​​ ​​​​
![@_4TEN(}%}A}5QVX_SIT8DX](https://user-images.githubusercontent.com/872655/197129734-a1fc9612-c603-4773-8c30-c08d8d061dc4.png)

**Comment by codefollower** [comment]
问题修复了，更新一下 lealone-plugins 和 lealone 的最新代码。
跟 spring boot 集成时默认让 lealone 禁用动态编译功能，退回到反射的方式，spring boot 打包后不支持 java compiler。

如果是 windows 平台，可以直接使用 build.bat 打包和运行例子
打包 build -p
运行 build -r

非 windows 平台
打包 mvn package -Dmaven.test.skip=true
运行 java -jar ./target/lealone-spring-demo-1.0.0.jar


mvn spring-boot:run 可以不打包直接运行，主要用于开发测试阶段，
不过开发测试阶段直接在 IDE 里运行 org.lealone.examples.spring.SpringDemo 即可。
