### ISSUE TITLE
请求http://localhost:8080/service/test_service/hello?name=zhh报错500，Class "org.lealone.examples.spring.executor.TestServiceExecutor" not found

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#19]
使用官方例子自己在写了一个
`public class TestService {
    // 用这样的url打开: http://localhost:8080/service/hello_service/hello?name=zhh
    public String hello(String name) {
        return "Hello " + name;
    }

    public static void create() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:lealone:embed:lealone", "root", "");
            String sql = "create service if not exists test_service (hell(name varchar) varchar)" //
                    + " implement by '" + TestService.class.getName() + "'";
            conn.createStatement().executeUpdate(sql);
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}`

在 ServletInitializer和SpringDemo加上了TestService.create();

**Comment by codefollower** [comment]
已经不使用org.lealone.examples.spring.executor.TestServiceExecutor的方式调用服务了，这个类是动态生成的，spring boot 不支持 java compiler 动态编译，所以我几个小时前才修改了实现。还没有把最新 jar 包部署到 maven 仓库。

你需要下载 lealone 和 lealone-plugins 这两个项目的代码，然后把它们安装到本地的 maven 仓库，这样就能用到最新的版本了。

**Comment by codefollower** [comment]
已经不使用org.lealone.examples.spring.executor.TestServiceExecutor的方式调用服务了，这个类是动态生成的，spring boot 不支持 java compiler 动态编译，所以我几个小时前才修改了实现。还没有把最新 jar 包部署到 maven 仓库。

你需要下载 lealone 和 lealone-plugins 这两个项目的代码，然后把它们安装到本地的 maven 仓库，这样就能用到最新的版本了。

**Comment by codefollower** [comment]
Maven Central Repository 今天有问题，新 jar 包部署都失败了，你只能下载源代码然后用 mvn install -Dmaven.test.skip=true 安装到本地的 maven 仓库了。

**Comment by zoujiegogogo** [comment]
好的，如果可以在补充一些命令和铺垫理论知识那最好了，来完善Lealone官方文档会更加快速上手这个框架开发。比如：mvn clean install -Dmaven.test.skip=true -U让项目打包的文件自动打包到idea默认设置的仓库目录，今天没注意导致用了不少的时间终于跑起来了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月22日(星期六) 中午12:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lealone/Lealone-Examples] 请求http://localhost:8080/service/test_service/hello?name=zhh报错500，Class &quot;org.lealone.examples.spring.executor.TestServiceExecutor&quot; not found (Issue #19)





 
已经不使用org.lealone.examples.spring.executor.TestServiceExecutor的方式调用服务了，这个类是动态生成的，spring boot 不支持 java compiler 动态编译，所以我几个小时前才修改了实现。还没有把最新 jar 包部署到 maven 仓库。
 
你需要下载 lealone 和 lealone-plugins 这两个项目的代码，然后把它们安装到本地的 maven 仓库，这样就能用到最新的版本了。

**Comment by codefollower** [comment]
lealone 是一个标准的 maven 项目，你最好独自下载一个 maven 到你的本机上，然后把它的 bin 目录加到 path 环境变量里，最后再依据你使用的具体操作系统修改一下它的 settings.xml 文件把里面的仓库目录设置一下就可以啦。

idea 和 eclipse 都能自动识别你本机上面的 maven  的，每个人都有自己喜欢的 ide，一个开源项目不可能只是为某个 ide 设计，只要是一个标准的 maven 项目即可，然后各个 ide 就能统一的识别 maven 项目了。配置好了 maven 之后，使用标准的 mvn install 命令就能把 jar 包安装到前面配置好的仓库目录，然后所有 ide 都能找到 maven 打包后的 jar 包了。

maven 是 java 开发的基础知识了，如果一个项目带有 pom.xml，那它就是 maven 项目，每遇到一个 maven 项目，别人一般都不会从头写文档介绍怎么使用 maven 的，这个需要你自己去找 maven 的文档来看。
