### ISSUE TITLE
在使用lealone-xsql-5.0.0.jar出现的问题：org.lealone.common.exceptions.DbException: Create database rights are required for this operation [90143-0]

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#20]
在lealone数据库是不能自己创建数据库吧，如果使用mysql --no-beep -h localhost -P 9310 -u root进去之后，执行创建数据库，会报错
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by codefollower** [comment]
create database 语句对用户权限的要求很高，只有用内置的名叫 lealone 的数据库中的 root 用户才有权限执行。
用 mysql --no-beep -h localhost -P 9310 -u root 连上去，实际上默认用的是内置的名叫 mysql 的数据库，这个数据库中的 root 用户没有执行 create database 语句的权限。

如果使用 mysql --no-beep -h 127.0.0.1 -P 9310 -u root -D lealone 的方式连上去，
因为 lealone 用的密码加密算法跟 mysql 客户端用的算法是不同的，所以就会造成冲突。

现在只有一种办法，就是用 lealone 的客户端用 root 连上 lealone 数据库，然后创建适合 mysql 访问的数据库
**`create database mydb parameters(default_sql_engine='mysql')`**
这样的数据库才能用 mysql 客户端连。

**Comment by codefollower** [comment]
你可以下载最新的 http://lealone.org/download/lealone-xsql-5.0.0.jar

然后用 java -jar lealone-xsql-5.0.0.jar 启动
接着用 java -jar lealone-xsql-5.0.0.jar -client 启动 lealone 的客户端，在里面执行以下 sql:
create database mydb parameters(default_sql_engine='mysql')

最后用 mysql --no-beep -h 127.0.0.1 -P 9310 -u root -D mydb 就能连到新的数据库了。

因为 lealone 要兼容 lealone、mysql、postgresql 的客户端，每个客户端的密码加密算法都不一样，所以每个数据库里的用户就不能一样。

**Comment by codefollower** [comment]
还需要补充一下，lealone 跟 mysql 的数据库对象模型是不同的，
mysql 的 database 和 schema 是同义词，lealone 的 schema 是 database  的下级。

所以当你用 mysql 客户端连上去时，执行 use xxx 时，这个 xxx 是 schema 不是 database。
