### ISSUE TITLE
开发一个接口的步骤有哪些？遇到一个问题：Exception in thread "main" org.lealone.common.exceptions.JdbcSQLException: Syntax error in SQL statement "

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#21]
在tables.sql就是创建一个表，就有问题，不知道咋解决
`create table if not exists test(
    name varchar
)`
我就只定义了这些，就会报错

**Comment by codefollower** [comment]
出现 Syntax error in SQL statement，就是 SQL 写错了，看看错误提示里的 [*] 出现在哪里就代表哪里有错。
如果你只是用 Lealone  开发微服务接口，就按这篇文章操作就好: [Lealone 微服务框架快速入门](http://lealone.org/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A1%86%E6%9E%B6%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html)

如果只是用 Lealone ORM 框架读写数据库看这篇：[Lealone ORM 框架快速入门](http://lealone.org/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/Lealone%20ORM%E6%A1%86%E6%9E%B6%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html)

如果同时用 Lealone  开发微服务接口，然后在服务实现类里调用  Lealone ORM 框架读写数据库看这篇：
[使用 Lealone RPC 和 ORM 框架开发一个全栈微服务应用](http://lealone.org/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E4%BD%BF%E7%94%A8Lealone%20RPC%E5%92%8CORM%E6%A1%86%E6%9E%B6%E5%BC%80%E5%8F%91%E4%B8%80%E4%B8%AA%E5%85%A8%E6%A0%88%E5%BE%AE%E6%9C%8D%E5%8A%A1%E5%BA%94%E7%94%A8.html)

**Comment by codefollower** [comment]
把 [Lealone-Examples](https://github.com/lealone/Lealone-Examples) 里的例子导入到你的 IDE 里运行，对着文档看看就好了。

**Comment by zoujiegogogo** [comment]
我是使用fullstack-demo作为模板使用，然后我创建服务托管一个新的serviceImpl，然后就报Exception in thread "main" org.lealone.common.exceptions.JdbcSQLException: Table "USER" not found; SQL statement，我就很懵逼

**Comment by codefollower** [comment]
如果是 fullstack-demo，把你的 create table if not exists test( name varchar ) 加到 tables.sql
然后运行 org.lealone.examples.fullstack.FullStackDemo，就会自动运行 tables.sql 和 services.sql，建表建服务。
如果你已经启动 FullStackDemo 了，然后才往 tables.sql 加建表语句，那肯定找不到表的，重启 FullStackDemo 就好了。

**Comment by codefollower** [comment]
在 tables.sql 中，语句和语句之间用分号分隔，如果你忘记加分号了就容易出现语法错误，当成一条语句处理了。

**Comment by zoujiegogogo** [comment]
![image](https://user-images.githubusercontent.com/48706279/197539620-b0b7553d-1945-4c1a-96bb-42f7eda8f833.png)
我先确定下这个有没有问题？

**Comment by zoujiegogogo** [comment]
![image](https://user-images.githubusercontent.com/48706279/197540020-a5750168-9432-4ac3-ba7c-21240075791a.png)
我这里是引用最新的修改，但是还是报错

**Comment by codefollower** [comment]
错了，package 和 generate code 那是 create table 语句的一部分
你看看 petstore 的 [tables.sql](https://github.com/lealone/Lealone-Examples/blob/main/petstore/petstore-dal/src/main/resources/tables.sql)

**Comment by zoujiegogogo** [comment]
好的

**Comment by zoujiegogogo** [comment]
学会了，感谢

**Comment by codefollower** [comment]
不用客气，遇到不能理解的问题随时可以发出来。

**Comment by zoujiegogogo** [comment]
会的，哈哈
