### ISSUE TITLE
运行java -jar lealone-xsql-5.0.0.jar,运行mysql --no-beep -h localhost -P 9310 -u root报错，这个是啥原因

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#22]
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
![image](https://user-images.githubusercontent.com/48706279/197769541-18b33b74-4b25-4d63-bb7f-e013c606a389.png)
![image](https://user-images.githubusercontent.com/48706279/197769574-c85efa49-413b-4a06-aed3-8fe30ff0cdf0.png)

**Comment by zoujiegogogo** [comment]
我现在想要看orm-demo运行的新建表有没有成功，想要查一下，该咋弄呢？

**Comment by codefollower** [comment]
java -jar lealone-xsql-5.0.0.jar -client -database xxx

**Comment by zoujiegogogo** [comment]
报错Exception: org.lealone.common.exceptions.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: no further information: localhost:9210" [90067-0]
![image](https://user-images.githubusercontent.com/48706279/197774833-ca283cbb-d429-4c09-b860-5a260cca1de1.png)
![image](https://user-images.githubusercontent.com/48706279/197774863-329fa868-37a5-40dc-b818-f2da36e2cc9b.png)

**Comment by codefollower** [comment]
启动数据库 java -jar lealone-xsql-5.0.0.jar -baseDir orm-demo\target\lealone_db_base_dir

启动客户端 java -jar lealone-xsql-5.0.0.jar -client -database test

**Comment by zoujiegogogo** [comment]
ok，解决了

**Comment by codefollower** [comment]
我看了一下，应该还有 bug，OrmDemo跑完后没有创建用户，client 是连不上的
把那个 url 改成 jdbc:lealone:embed:test?user=root 才能连上去

**Comment by codefollower** [comment]
mysql 客户端只能连 create database mydb parameters(default_sql_engine='mysql') 创建的数据库
当你用 mysql --no-beep -h localhost -P 9310 -u root 连数据库时，连的是 lealone mysql 插件创建的 mysql 数据库

**Comment by zoujiegogogo** [comment]
改成 jdbc:lealone:embed:test?user=root 报错The file is locked: nio:.\target\lealone_db_base_dir\redo_log\redoLog_0 [5.0.0/7]
![image](https://user-images.githubusercontent.com/48706279/197781345-417628ee-738b-4059-97ac-b69497e6a503.png)

**Comment by zoujiegogogo** [comment]
噢噢

**Comment by zoujiegogogo** [comment]
![image](https://user-images.githubusercontent.com/48706279/197782073-5faad038-0d05-468f-b265-98dc28c0e8a5.png)
![image](https://user-images.githubusercontent.com/48706279/197782214-0d0efce3-9621-4f9e-8c6e-ebd92cffaeb0.png)
我现在是启动数据库，但还是连接不上。

**Comment by codefollower** [comment]
mysql 客户端只能连 create database mydb parameters(default_sql_engine='mysql') 创建的数据库
当你用 mysql --no-beep -h localhost -P 9310 -u root 连数据库时，连的是 lealone mysql 插件创建的 mysql 数据库

OrmDemo 创建的是 create database test parameters(default_sql_engine='lealone ')  数据库，所以 mysql 客户端无法访问。

**Comment by codefollower** [comment]
删除 orm-demo\target\lealone_db_base_dir 目录，运行一遍 OrmDemo，然后再启动数据库即可

如果 url 是 jdbc:lealone:embed:test
客户端就要 java -jar lealone-xsql-5.0.0.jar -client -url jdbc:lealone:tcp://localhost:9210/test?user=

如果 url 是 jdbc:lealone:embed:test?user=root
客户端就要 java -jar lealone-xsql-5.0.0.jar -client -url jdbc:lealone:tcp://localhost:9210/test?user=root

或者 java -jar lealone-xsql-5.0.0.jar -client -database test，跟上面的等价

**Comment by zoujiegogogo** [comment]
可以了，那就是开一个项目，就需要去手动启动一下lealone这个数据库，然后这个数据库数据目录要指向编译后的数据目录是吧

**Comment by codefollower** [comment]
lealone 分成嵌入式 和 client server 模式，这个 orm-demo 就是通过嵌入式来读写那个叫 test 的数据库，如果你想通过 client 远程访问，就得转到 client server 模式。

orm-demo 那个例子如果想通过嵌入式来读写那个叫 test 的数据库，又想让 client 能远程访问，
你需要在 pom.xml 中加上
```xml
        <dependency>
            <groupId>org.lealone</groupId>
            <artifactId>lealone-main</artifactId>
            <version>5.0.0</version>
        </dependency>
```

然后修改 org.lealone.examples.orm.OrmDemo 类的 main 方法
```java 
    public static void main(String[] args) throws Exception {
        createTable();
        testCrud();
        testJoin();
        testTransaction();

        //多加上这一行
        org.lealone.main.Lealone.main(new String[] { "-baseDir", "target/lealone_db_base_dir" });
    }
```

**Comment by zoujiegogogo** [comment]
还有一个问题，语法和表名必须大写查出来报错，其他2张表查出来都没问题
![image](https://user-images.githubusercontent.com/48706279/197793224-55e4e6eb-f531-413c-b636-707e7d9bc579.png)

**Comment by codefollower** [comment]
order 是 sql 关键字，用 `order` 替换，tables.sql 里提到了

**Comment by zoujiegogogo** [comment]
![image](https://user-images.githubusercontent.com/48706279/197794118-1802b551-697b-45bd-b186-227838fa8efa.png)
![image](https://user-images.githubusercontent.com/48706279/197794257-2454b7f3-5846-40b5-966c-850cc8e520b8.png)
你看看

**Comment by codefollower** [comment]
不是单引号，从 tables.sql 里面 copy，这个 mysql 也是一样的， 是`

**Comment by zoujiegogogo** [comment]
好的
