### ISSUE TITLE
可以教教咋使用DBeaver连接Lealone数据库不？不能检索lealone驱动

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#23]
![image](https://user-images.githubusercontent.com/48706279/197937972-ad60550b-5070-49fe-8966-e94c261c1a90.png)

**Comment by codefollower** [comment]
![image](https://user-images.githubusercontent.com/872655/197940942-d263ce59-c570-4b7e-a8f8-e355d254ad43.png)

**Comment by zoujiegogogo** [comment]
![微信截图_20221026132249](https://user-images.githubusercontent.com/48706279/197941715-4996cc77-3569-4c4b-a310-3ee58fcf8c9b.png)
没有，我是下载最新版本DBeaver

**Comment by codefollower** [comment]
点 数据库 -> 驱动管理器 -> 新建
![image](https://user-images.githubusercontent.com/872655/197942458-dbe159dd-a77e-425a-850d-d60a566077a1.png)

**Comment by codefollower** [comment]
配置驱动
org.lealone.client.jdbc.JdbcDriver
jdbc:lealone:tcp://{host}[:{port}]/[{database}]

![image](https://user-images.githubusercontent.com/872655/197943806-64b24594-7f54-43a1-9a8b-8e25e3e0ba70.png)
![image](https://user-images.githubusercontent.com/872655/197943843-004bdef4-3588-4cc8-8223-15cb3278b031.png)

**Comment by zoujiegogogo** [comment]
ok，没问题了

**Comment by processdatatech** [comment]
问题:
Reason: can't load driver class 'org.lealone.client.jdbc.JdbcDriver'
  Error creating driver 'lealone' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'org.lealone.client.jdbc.JdbcDriver'
    org/lealone/db/async/Future
    org/lealone/db/async/Future
      org.lealone.db.async.Future
      org.lealone.db.async.Future

**Comment by codefollower** [comment]
lealone 6.0 的包名从 org.lealone 改成 com.lealone 了。

**Comment by processdatatech** [comment]
是lealone-client-5.2.1.jar，在dbeaver 中添加驱动包后，创建连接报上面的错误

**Comment by codefollower** [comment]
> 是lealone-client-5.2.1.jar，在dbeaver 中添加驱动包后，创建连接报上面的错误

点 数据库 -> 驱动管理器 -> 新建
再点 “库-> 添加文件"，把 lealone-client-5.2.1.jar 加进去就好了。

如果已经存在，就编辑一下，删除旧的添加新的。

我测试了 lealone-client-5.2.1.jar 没问题的。

还提示找不到 org.lealone.client.jdbc.JdbcDriver 就关掉 dbeaver 重新打开，刷新还失败就删掉现有的连接，重新建。

**Comment by processdatatech** [comment]
还是不行，本来以为是jdk 版本问题，切换到jdk1.8.0_321，任然报错。lealone-client-5.2.1.jar，我用的是这个版本，6.0 的版本哪里能获取到?

**Comment by codefollower** [comment]
> 还是不行，本来以为是jdk 版本问题，切换到jdk1.8.0_321，任然报错。lealone-client-5.2.1.jar，我用的是这个版本，6.0 的版本哪里能获取到?

[lealone-6.0.0-SNAPSHOT.jar](https://github.com/lealone/Lealone-Docs/releases/download/lealone-docs-1.0.0/lealone-6.0.0-SNAPSHOT.jar)

**Comment by codefollower** [comment]
都是标准的 jdbc 驱动，拿 lealone-client-5.2.1.jar 在你的电脑上跑以下代码，如果能正常跑那一定是你的 dbeaver 没有在类路径中找到 lealone-client-5.2.1.jar 这个包，清理缓存重新建一下就好了。

```java
import java.sql.*;

public class CRUDExample {
    public static void main(String[] args) throws Exception {
        String url = "jdbc:lealone:tcp://localhost:9210/lealone";
        Connection conn = DriverManager.getConnection(url, "root", "");
        Statement stmt = conn.createStatement();

        stmt.executeUpdate("CREATE TABLE IF NOT EXISTS test (f1 int primary key, f2 long)");
        stmt.executeUpdate("INSERT INTO test(f1, f2) VALUES(1, 1)");
        stmt.executeUpdate("UPDATE test SET f2 = 2 WHERE f1 = 1");
        ResultSet rs = stmt.executeQuery("SELECT * FROM test");
        while (rs.next()) {
            System.out.println("f1=" + rs.getInt(1) + " f2=" + rs.getLong(2));
            System.out.println();
        }
        rs.close();
        stmt.executeUpdate("DELETE FROM test WHERE f1 = 1");
        stmt.executeUpdate("DROP TABLE IF EXISTS test");
        stmt.close();
        conn.close();
    }
}
```

**Comment by processdatatech** [comment]
lealone-6.0.0 对于的client 也是5.2.1 么？

**Comment by codefollower** [comment]
lealone 6 那个 jar 包是通用的，里面也包含了 jdbc client 端的代码，既能连 5.2.1 版本的数据库，也能连 6.0。你这个问题我敢肯定不是 jar 包出了问题，我的 DBeaver 用这两个版本的 jar 包都是能联通了，大概率就是你用的 DBeaver 的版本问题，或者哪里的配置配错了或不起作用。你就照着这个帖子最初的那几个截图重新配置就好了。都是走标准的 jdbc 驱动，并没有特殊的地方，你也可以用 mysql 或 h2 数据库的 jdbc client 测试一下看看 DBeaver 到底哪里配错了。

**Comment by processdatatech** [comment]
切换lealone-6.0.0-SNAPSHOT.jar 正常了，lealone-client-5.2.1.jar还是存在问题

**Comment by processdatatech** [comment]
我的lealone-client-5.2.1.jar 包是从mave repo 中获取的。刚测了下，上一页的5.2.1的包是正常的

**Comment by codefollower** [comment]
> 我的lealone-client-5.2.1.jar 包是从mave repo 中获取的。刚测了下，上一页的5.2.1的包是正常的

从 maven repo 下的包是不包含依赖的，lealone-client 依赖了 lealone-net 和 lealone-common。

需要下载 [lealone-5.2.1.jar](https://github.com/lealone/Lealone/releases/download/lealone-5.2.1/lealone-5.2.1.jar) 或者 [lealone-client-5.2.1.jar](https://github.com/lealone/Lealone/releases/download/lealone-5.2.1/lealone-client-5.2.1.jar) 这个包含了 lealone-net 和 lealone-common 的完整包。
