### ISSUE TITLE
如何解决在不用重启动数据库和server的情况下，新增一个微服务类

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#26]
我平时就是把 lealone 内嵌到应用中启动，然后在 services.sql 文件中定义服务，改完了直接执行这个 sql 文件就会给我创建出对应的 java 实现类，最后我再去这些 java 类的空方法里填代码就好了（[链接](https://share.api.weibo.cn/share/344066823,4827280294284159.html?weibo_id=4827280294284159)）
疑惑：
改完直接执行sql文件，这不还是要重启应用来生成对应的 java 实现类嘛？

**Comment by codefollower** [comment]
你试一下那个 pet store，orm 和微服务框架全是内嵌数据库的，但是也启动了 tcp server，里面运行 sql 脚本的程序是远程连接的，生成的代码会放在 src 目录下，如果你是通过 debug 模式启动 pet store，除非是删除或新增方法，否则不用重启 eclipse 或 idea 都能热加载 java 代码。我有时哪怕在 debug 代码的过程中执行 sql 脚本，eclipse 都能自动加载新代码，然后从方法的第一行开始调试。

一定要用 debug 模式启动。

**Comment by codefollower** [comment]
我告诉你怎么体验:
先把 petstore 的代码导入到 idea 或 eclipse 中
然后用 debug 模式启动 org.lealone.examples.petstore.test.PetStoreTest
接着运行 org.lealone.examples.petstore.test.PetStoreSqlScriptTest，这一步会第一次执行所有的 sql 脚本
执行完后你打开 http://localhost:9000/ 就能看到 petstore 的主页了。

接着假定你想增加一个新服务，你需要打开 /petstore-service/src/main/resources/services.sql
然后在最后增加以下新的 sql:
```sql
drop service if exists my_service;
create service if not exists my_service (
  test(name varchar) varchar
)
implement by 'org.lealone.examples.petstore.service.MyService'
code path '../petstore-service/src/main/java'; -- idea 要改成 './petstore-service/src/main/java'
```

保存后，重新运行一下 org.lealone.examples.petstore.test.PetStoreSqlScriptTest
这时你刷新一下 petstore-service 模块，里面多了一个 MyService.java

然后你再打开 [http://localhost:9000/service/my_service/test?name=zhh](http://localhost:9000/service/my_service/test?name=zhh)

此时浏览器返回的是 null，不是 zhh
然后你打开 MyService.java，把代码改成下面这样:
```java
package org.lealone.examples.petstore.service;

public class MyService {
    public String test(String name) {
        return name;
    }
}
```
保存后，再刷新一下浏览器，结果就返回 zhh
完整体验下来你都不用重启动 petstore 的

**Comment by zoujiegogogo** [comment]
非常感谢大哥的回答，大哥真有耐心。我遇到了一个问题：在用debug模式启动PetStoreTest，报错Failed to init transaction engine: AOTE，The file is locked: nio:./target/data\redo_log\redoLog_0 [5.0.0/7]。在报这个错误之前解决端口被占用的问题（之前开了一个数据库），解决完之后出现了这个问题

**Comment by codefollower** [comment]
你把那个进程停掉就可以了，两个进程是不允许打开 lealone 的文件的。

**Comment by zoujiegogogo** [comment]
关闭eclipse工具，重新启动好了。
