### ISSUE TITLE
eclipse玩法问题

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#27]
之前对eclipse工具的理解就是工具老，感觉没idea直观，在用旗舰版有问题看csdn都能解决相关问题，我翻了所有关于eclipse的旧微博，里面提到了一种学习开源项目的方法：使用eclipse工具来远程调试。这是咋整的呀？

**Comment by zoujiegogogo** [comment]
[旧微博链接](https://share.api.weibo.cn/share/344070598,4351668907201570.html?weibo_id=4351668907201570)

**Comment by codefollower** [comment]
这种基础工具的使用自己搜一下吧，很多的，搜 eclipse 远程调试

**Comment by codefollower** [comment]
都内嵌 lealone 数据库了，eclipse 远程调试对于 lealone 用处不大，除非你把 lealone 部署到远程的服务器，然后用 debug 模式启动它，这时在你本机用 idea  或 eclipse 远程调试才有意义。

**Comment by codefollower** [comment]
[lealone-5.0.0.tar.gz](https://github.com/lealone/Lealone/releases/download/lealone-5.0.0/lealone-5.0.0.tar.gz)
[lealone-5.0.0.zip](https://github.com/lealone/Lealone/releases/download/lealone-5.0.0/lealone-5.0.0.zip)

这是两个 leaone 的完整部署包，只是压缩格式不同，有启动脚本的，解压后切换到 bin 目录，输入 lealone 就能正常启动，输入 lealone -debug 就能用 debug 模式运行，然后就能用 idea 或 eclipse 远程调试了。
