### ISSUE TITLE
使用spring-demo例子，依赖下载不到，手动build -p也不行，是需要拉代码打包jar放到这个项目里面嘛？

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#28]
![image](https://user-images.githubusercontent.com/48706279/209036287-2562c30a-36a9-4ad4-96a4-19476c28a860.png)
![image](https://user-images.githubusercontent.com/48706279/209036423-2d393a0c-3b04-499d-ba90-875bdabacc76.png)

**Comment by zoujiegogogo** [comment]
![image](https://user-images.githubusercontent.com/48706279/209036563-8584d63b-4e98-44d5-911d-8556b158d0b6.png)

**Comment by codefollower** [comment]
lealone 5.1.0 还没有上传到 maven 依赖中心，你暂时改成 5.0.0 吧。

**Comment by zoujiegogogo** [comment]
噢噢，好的

**Comment by zoujiegogogo** [comment]
现在发release了，好像还是没上传阿里云maven镜像吧

**Comment by codefollower** [comment]
阿里云同步比较慢，它会从 maven 中央仓库同步，一般都要两三天以上，maven 中央仓库昨天就已经有了。

**Comment by zoujiegogogo** [comment]
噢噢，原来如此！

**Comment by codefollower** [comment]
阿里云的 maven 仓库已近把 lealone 的最新版本同步过去了，确实比较慢。
