### ISSUE TITLE
petstore 启动报错, 打包报错

### ISSUE THREAD

**Issue by gongsongping** [lealone/Lealone-Examples#29]
今天拉了最新的代码, 有两个报错:
1, 
petstore-test里的lealone.yaml 改成 jdbc_url: "jdbc:lealone:tcp://localhost/petstore?user=root&password="
启动报:
ERROR 17:49:14.959 Fatal error: unable to start lealone. See log for stacktrace.
java.lang.ClassCastException: org.lealone.client.session.ClientSession cannot be cast to org.lealone.db.session.ServerSession

2, build -p 打包的时候
报:
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project petstore-service: Fatal error compiling: 无效的标记: --release -> [Help 1]

**Comment by codefollower** [comment]
lealone.yaml 里的 jdbc_url 只能是嵌入式的 jdbc:lealone:embed:petstore?user=root&password=
微服务框架通过嵌入式的方式创建 ServerSession，然后检查当前 url 中的用户是否有执行服务的权限。

出现 **无效的标记: --release** 需要升级 jdk 到9以上，或者直接把 pom.xml 中的 `<release>8</release>`删除即可。
