### ISSUE TITLE
Lealone整合问题

### ISSUE THREAD

**Issue by zoujiegogogo** [lealone/Lealone-Examples#30]
Lealone如何整合Redis，MongoDB，整合springsecurity这些框架去使用呢？是否跟springboot整合是一样的嘛？

**Comment by zoujiegogogo** [comment]
如果只是单单引入Lealone的话

**Comment by codefollower** [comment]
不需要整合 Redis，MongoDB 的，只要用它们的 java 客户端，
然后在你的 lealone 微服务应用代码里调用它们的  java 客户端就可以了。

如果在 springboot 里把 lealone 当成一个组件使用了，就像这个 [在Spring现有应用中使用Lealone微服务框架](https://github.com/lealone/Lealone-Docs/blob/master/%E5%BA%94%E7%94%A8%E6%96%87%E6%A1%A3/%E5%9C%A8Spring%E7%8E%B0%E6%9C%89%E5%BA%94%E7%94%A8%E4%B8%AD%E4%BD%BF%E7%94%A8Lealone%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A1%86%E6%9E%B6.md)
那你还是像原来在 spring 应用中那样使用 springsecurity，最多就是写个 url 拦截器来拦截一下调用 lealone 微服务的 url，
lealone 微服务的 url 默认是 /service/<service_name>/<method_name>。

**Comment by codefollower** [comment]
这里有个 springsecurity 的例子，像代码示例中那样配置一下 /service/** 就能拦截 lealone 的微服务调用了。
https://www.cnblogs.com/demingblog/p/10874753.html
```java
@Configuration
@EnableWebSecurity
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                    .antMatchers("/service/**").hasRole("USER")
                .anyRequest().authenticated()
                .and()
                .formLogin().and()
                .httpBasic();
     }

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth
            .inMemoryAuthentication()
            .withUser("spring").password("{noop}123456").roles("USER");
     }
}
```
