### ISSUE TITLE
依赖的org.lealone.plugins:lealone-spring:6.0.0-SNAPSHOT 找不到 

### ISSUE THREAD

**Issue by dbgp** [lealone/Lealone-Examples#31]
https://repo1.maven.org/maven2/org/lealone/plugins/lealone-spring/ 只有正式版本

spring-demo依赖 

```
 <dependency>
            <groupId>org.lealone.plugins</groupId>
            <artifactId>lealone-spring</artifactId>
            <version>6.0.0-SNAPSHOT</version>
        </dependency>
```

这个lealone-spring插件的父依赖也找不到

```
<parent>
        <groupId>org.lealone.plugins</groupId>
        <artifactId>lealone-plugins</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>
```

使用的maven配置文件

```
<settings
	xmlns="http://maven.apache.org/SETTINGS/1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
	<pluginGroups/>
	<proxies/>
	<servers></servers>
	<mirrors>
		<!-- 阿里云仓库 -->
		<mirror>
			<id>alimaven</id>
			<mirrorOf>central</mirrorOf>
			<name>aliyun maven</name>
			<url>https://maven.aliyun.com/repository/central</url>
		</mirror>
		<!-- 中央仓库1 -->
		<mirror>
			<id>repo1</id>
			<mirrorOf>central</mirrorOf>
			<name>Human Readable Name for this Mirror.</name>
			<url>https://repo1.maven.org/maven2/</url>
		</mirror>
	</mirrors>
	<profiles>
		<repositories>
			<repository>
				<id>snapshot-repository</id>
				<url>https://oss.sonatype.org/content/repositories/snapshots</url>
				<releases>
					<enabled>false</enabled>
				</releases>
				<snapshots>
					<enabled>true</enabled>
				</snapshots>
			</repository>
		</repositories>
	</profiles>
	<activeProfiles></activeProfiles>
</settings>
```

**Comment by codefollower** [comment]
6.0.0-SNAPSHOT 这个版本目前都还没有上传到仓库

如果要测试的话，需要手工安装到本地仓库，步骤如下，假设是 windows 系统，其他系统改一下路径即可

第一步下载 lealone 6.0.0 以及几个插件的代码

git clone https://github.com/lealone/Lealone.git E:/lealone/lealone-6
git clone https://github.com/lealone-plugins/lealone-orm.git E:/lealone/lealone-plugins/lealone-orm
git clone https://github.com/lealone-plugins/lealone-service.git E:/lealone/lealone-plugins/lealone-service
git clone https://github.com/lealone-plugins/lealone-tomcat.git E:/lealone/lealone-plugins/lealone-tomcat
git clone https://github.com/lealone-plugins/lealone-spring.git E:/lealone/lealone-plugins/lealone-spring

第二步按先后顺序进入以上各项目的目录都执行以下命令安装到本地仓库

mvn install -Dmaven.test.skip=true

执行完以上两步后，spring-demo 的所有依赖就能找到了。

**Comment by dbgp** [comment]
```
<dependency>
            <groupId>org.lealone</groupId>
            <artifactId>lealone-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
<!--            <classifier>tests</classifier>-->
        </dependency>
```

把对test依赖中的 `classifier`字段注释之后，可以编译安装正常，否则报错类似——

[ERROR] Failed to execute goal on project lealone-orm: Could not resolve dependencies for project org.lealone.plugins:lealone-orm:jar:6.0.0-SNAPSHOT: Could not find artifact org.lealone:lealone-test:jar:tests:6.0.0-SNAPSHOT -> [Help 1]

**Comment by codefollower** [comment]
把 -Dmaven.test.skip=true 去掉才会产生 lealone-test:jar
