### ISSUE TITLE
做了以下调整才可以正常run起来？

### ISSUE THREAD

**Issue by runc** [lealone/Lealone-Examples#4]
![image](https://user-images.githubusercontent.com/1925916/103747591-ddd6c880-503d-11eb-8570-7970b4065053.png)

fix1:

![image](https://user-images.githubusercontent.com/1925916/103747663-f2b35c00-503d-11eb-8e67-bb79e65fe632.png)

fix2:
![image](https://user-images.githubusercontent.com/1925916/103747733-0d85d080-503e-11eb-8761-9432f4629255.png)

fix3:
![image](https://user-images.githubusercontent.com/1925916/103747771-1d051980-503e-11eb-8134-1838d3c3b9ab.png)

fix4:
![image](https://user-images.githubusercontent.com/1925916/103747828-34dc9d80-503e-11eb-9119-a4b6c5e0a358.png)

![image](https://user-images.githubusercontent.com/1925916/103747928-53db2f80-503e-11eb-894c-5a333535d7ea.png)

**Comment by runc** [comment]
有可能笔者使用的windows，或者eclipse上有特殊设置，我运行环境是mac+idea。

**Comment by runc** [comment]
建议在resource处理上参照spring，相对来说兼容性可能更好，也许不符合笔者简洁的初衷。

**Comment by codefollower** [comment]
@runc
图片挂了，显示不出来。
我用的确实是windows和eclipse

那些脚本都是bat的，在mac上不能直接运行，如果在mac上运行得把里面的命令单独抽出来执行，
比如 build -p 实际上是组合了以下三条命令

mvn package -Dmaven.test.skip=true

//这条用于编译thymeleaf模板文件
java -cp petstore-dist/target/lealone-petstore-1.0.0.jar org.lealone.examples.petstore.web.thymeleaf.ThymeleafTemplateCompiler -webRoot petstore-web/web -targetDir petstore-dist/target

//这条把jar包和web文件都抽取出来了
mvn assembly:assembly -Dmaven.test.skip=true

mac上面跑，得有shell脚本才行，不过你是idea的话，把代码导入进去能跑的吧，都是标准的maven项目。

**Comment by codefollower** [comment]
@runc
你更新一下代码试试，我新加了三个对应的shell脚本，在我的ubuntu上面能成功构建运行。
