### ISSUE TITLE
缺少 lealone.script.directory 异常

### ISSUE THREAD

**Issue by iDayMonthYear** [lealone/Lealone-Examples#7]
static void runScript(String scriptFile) throws Exception {
        System.setProperty("lealone.jdbc.url", jdbcUrl);
        System.setProperty("lealone.script.directory", "./");
        try (Connection conn = DriverManager.getConnection(jdbcUrl); Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("RUNSCRIPT FROM '" + scriptFile + "'");
        }
    }

好像要自己添加系统变量。否则会报异常 Exception in thread "main" org.lealone.common.exceptions.JdbcSQLException: IO Exception: "java.io.FileNotFoundException: .\target\db_base_dir\script_directory\.\src\main\resources\tables.sql (系统找不到指定的路径。)"; "./target/db_base_dir\script_directory\./src/main/resources/tables.sql"; SQL statement:

**Comment by iDayMonthYear** [comment]
https://github.com/lealone/Lealone-Examples/blob/main/fullstack-demo/src/main/java/org/lealone/examples/fullstack/FullStackDemo.java

**Comment by codefollower** [comment]
bug 已经 [修复](https://github.com/lealone/Lealone/commit/19132e5ed3dec56b370d95aeb82d2bf5e22dded9)

6月份时对代码做了一些修改，默认加上脚本目录名导致出错。

感谢报告 bug。
