### ISSUE TITLE
"SYSTEM_SEQUENCE_133C76D2_84EC_412B_BAFB_C503EFCAB271" not found;

### ISSUE THREAD

**Issue by iDayMonthYear** [lealone/Lealone-Examples#8]
```
set @packageName 'org.lealone.examples.fullstack.generated.model'; -- 生成的服务接口所在的包名
set @srcPath './src/main/java'; -- 生成的服务接口对应的源文件所在的根目录

drop table if exists user;
create table if not exists user (
  id long auto_increment primary key,
  name varchar,
  age int
) package @packageName generate code @srcPath;

drop table if exists t1;
create table if not exists t1 (
  id long auto_increment primary key,
  name varchar,
) package @packageName generate code @srcPath;

drop table if exists t2;
create table if not exists t2 (
  id long auto_increment primary key,
  name varchar,
) package @packageName generate code @srcPath;

drop table if exists t3;
create table if not exists t3 (
  id long auto_increment primary key,
  name varchar,
) package @packageName generate code @srcPath;
```

```

public class UserServiceImpl implements UserService {
    @Override
    public Long addUser(String name, Integer age) {
        Long userId =  new User().name.set(name).age.set(age).insert();
        new T1().name.set("t1-name").insert();
        new T2().name.set("t2-name").insert();
        new T3().name.set("t3-name").insert();
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ignored) {
        }
        return userId;
    }

    @Override
    public User findByName(String name) {
        return User.dao.where().name.eq(name).findOne();
    }
}

```
在页面上点添加返回结果后。不断重启 FullStackDemo 有时会出现下面异常。

Exception in thread "main" org.lealone.common.exceptions.JdbcSQLException: Sequence "SYSTEM_SEQUENCE_133C76D2_84EC_412B_BAFB_C503EFCAB271" not found; SQL statement:
CREATE CACHED TABLE PUBLIC.T3(
    ID LONG DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_133C76D2_84EC_412B_BAFB_C503EFCAB271) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_133C76D2_84EC_412B_BAFB_C503EFCAB271,
    NAME VARCHAR
) PARAMETERS(ISSHARDINGMODE='false')
PACKAGE 'org.lealone.examples.fullstack.generated.model'
GENERATE CODE './src/main/java' [90036-0]
	at org.lealone.common.exceptions.DbException.getJdbcSQLException(DbException.java:340)
	at org.lealone.common.exceptions.DbException.get(DbException.java:172)
	at org.lealone.common.exceptions.DbException.get(DbException.java:149)
	at org.lealone.db.schema.Schema.getSequence(Schema.java:626)

**Comment by codefollower** [comment]
我在 lealone 最新代码上按你的例子试了很多次，无法重现那个异常。

那个异常的原因是 auto_increment 会在内部自动创建一个 SEQUENCE，这个 SEQUENCE 也会对应一条 create 语句，lealone 会把这条 create 语句保存到一张 sys 表中，当加载数据库实例时，会去读这张 sys 表，然后执行里面的  create 语句，从而创建出 SEQUENCE 对象。

SEQUENCE 的创建顺序要先于 TABLE，如果在执行到 TABLE 的 create 语句时，找不到它依赖的 SEQUENCE 就会出现上面的异常。

所以异常原因可能是 SEQUENCE 对应的 create 语句没有保存到 sys 表中，导致在重新启动时就读不到了。

**Comment by codefollower** [comment]
我在 lealone 最新代码上按你的例子试了很多次，无法重现那个异常。

那个异常的原因是 auto_increment 会在内部自动创建一个 SEQUENCE，这个 SEQUENCE 也会对应一条 create 语句，lealone 会把这条 create 语句保存到一张 sys 表中，当加载数据库实例时，会去读这张 sys 表，然后执行里面的  create 语句，从而创建出 SEQUENCE 对象。

SEQUENCE 的创建顺序要先于 TABLE，如果在执行到 TABLE 的 create 语句时，找不到它依赖的 SEQUENCE 就会出现上面的异常。

所以异常原因可能是 SEQUENCE 对应的 create 语句没有保存到 sys 表中，导致在重新启动时就读不到了。

**Comment by iDayMonthYear** [comment]
这个只要出过一次错。就只能 mvn clean 后再重启才能解决了。
因为我是加一个表就重启一次。有时就会出这个错。

**Comment by iDayMonthYear** [comment]
我用的是最新的 lealone

**Comment by codefollower** [comment]
下次再遇到的话你打开 fullstack-demo\target\db_base_dir\redo_log\redoLog_0 文件，然后用异常中提示的 SEQUENCE 名搜索一下在不在里面，如果不在的话，就说明丢数据了。

mvn clean 会把所有的东西都删除，
删除 fullstack-demo\target\db_base_dir 目录就是直接删数据库的数据。

**Comment by codefollower** [comment]
在执行 mvn clean 之前，你可以把 fullstack-demo\target\db_base_dir 打包放上来，我排查一下原因

**Comment by codefollower** [comment]
在执行 mvn clean 之前，你可以把 fullstack-demo\target\db_base_dir 打包放上来，我排查一下原因

**Comment by iDayMonthYear** [comment]
[db_base_dir.zip](https://github.com/lealone/Lealone-Examples/files/7466060/db_base_dir.zip)

**Comment by iDayMonthYear** [comment]
大概知道啥问题了。如果有多张表的情况下。第一次重新启动还没结束马上重启会很容易出现这个问题。
如果只有一张表就没有出现这个问题。

**Comment by codefollower** [comment]
不能同时启动两个 lealone 进程的，事务引擎和存储引擎都会锁住它们要读写的文件，第二个 lealone 进程启动过程中碰到已经锁住的文件直接就抛错了。
你给的文件，我调试了一下，确实在 db_2/t_2_0/1 这个最新的数据文件里丢了一条 SEQUENCE 相关的记录，这个数据文件是做检查点时刷到硬盘的，做完检查点后 redolog 就清空了，所以你给的文件里 redolog 就没有内容了。

至于做检查点时刷到硬盘为什么丢？这个目前无法确定。另外做的两次检查点生成的两个数据文件 db_2/t_2_0/2 和 db_2/t_2_0/3 就没丢数据。

为什么会触发检查点呢？你是正常关闭 lealone 进程的？如果是直接在 ide 里面关闭，是属于非正常关闭，不会触发检查点。如果是在命令行窗口中按 ctrl+c，就是正常关闭 lealone 进程，会在关闭前触发检查点。

**Comment by codefollower** [comment]
我在命令行下用 ctrl+c 关闭 lealone 进程后再启动也能重现问题了，但是比较随机，这个 bug 估计挺费神，需要好好 debug 一下。

**Comment by codefollower** [comment]
感谢报告 bug，问题已经 fix。
